name: 'Standardrb Fix One File'
description: 'standardrb --fix を指定数ファイル自動で実行'
inputs:
  fix_count:
    description: '修正するファイル数'
    required: false
    default: '1'
  unsafe:
    description: 'unsafeな修正を許可するかどうか'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Backup .standard_todo.yml
      shell: bash
      run: |
        mv .standard_todo.yml .standard_todo.yml.bak
    - name: Extract file names and run standardrb --fix
      shell: bash
      run: |
        TARGET_FILES=$(yq '.ignore | .[] | keys | .[]' .standard_todo.yml.bak | shuf)
        FILES=$(echo "$TARGET_FILES" | { head -n ${{ inputs.fix_count }}; cat >/dev/null; })
        echo "Fixing $FILES"
        FIX_OPTION=${{ inputs.unsafe == 'true' && '--fix-unsafely' || '--fix' }}
        bundle exec standardrb $FIX_OPTION $FILES --format progress
    - name: Restore .standard_todo.yml
      shell: bash
      run: |
        mv .standard_todo.yml.bak .standard_todo.yml
